### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by cdeil** [jpivarski/pyminuit2#4]
@jpivarski Can you please add a license file to `pyminuit2`?

Here's what we use in `iminuit`:
https://github.com/iminuit/iminuit/blob/master/LICENSE

(I'm currently preparing a new iminuit release and want to add more docs ... the examples you have in the README are very nice and I also wanted to see if any of the tests should be added to iminuit.)

**Comment by jpivarski** [comment]
Would it be okay if I made it Apache v2? I use that for everything else and
it would be easier if I didn't have to learn a new license. I can't cover
the Minuit part, though. (I guess that's what your SEAL license is. Back
when I started this project, I contacted the CERN SEAL team directly and
asked about their license, and they said they hadn't thought about any
licensing. Times have changed.)

I might not get to adding the file (with the clarification that it applies
to my stuff, not CERN's) until Monday. But go ahead and assume that it'll
have a do-what-you-want Apache v2 license added in the near future.

Thanks for asking,
-- Jim

**Comment by cdeil** [comment]
Sounds great, thanks!

**Comment by jpivarski** [comment]
Oh, is GPLv2 okay? The original pyminuit was labeled as GPLv2 (https://github.com/jpivarski/pyminuit, see COPYING), which is something I used to do with everything. The overlap between pyminuit and pyminuit2 is pretty substantial. Something derived from GPLv2 can't easily be labeled Apache2 (or if it can, there's something I don't understand about the "infectious copyleft"), so I don't think I'd be allowed to make pyminuit2 Apache2. Does that limit what you want to do? (By the way, how much of iminuit is derived from pyminuit/pyminuit2?)

**Comment by cdeil** [comment]
I only wanted to add docs / tests to `iminuit` in the coming days and for that look at the `pyminuit` docs / tests. I don't know if doing this for docs / tests (as opposed to implementation) is a license violation ... unless you mention here it's OK I'll just not do it, no big problem.

I don't know if any code in iminuit is derived from pyminuit ... I think only the API was emulated: http://stackoverflow.com/a/20088271/498873

PS: @jpivarski – If you still have some time / are interested, it would be awesome to have your feedback on some of the iminuit issues (https://github.com/iminuit/iminuit/issues) or if you became a co-maintainer there. The split doesn't help the overall adoption (see my comment here: https://github.com/iminuit/iminuit/issues/156) of MINUIT from Python.

**Comment by jpivarski** [comment]
Okay, I've made the PyMinuit/PyMinuit2 licenses consistent, started using the modern convention of calling the license file "LICENSE", rather than "COPYING", and put big banners on the top of the two projects directing everybody to iminuit.

I'm not interested in maintaining a new version of this. In fact, I don't have any special expertise anymore; whatever I figured out the first time around is long forgotten. Anyone who can glue together Python and C++ can do it.

I think copying GPL'ed documentation is fine, since that documentation could never find its way into a commercial distribution. (It's more of an issue for libraries that are internally used without presenting themselves as such to the user--- by definition, documentation is for a user to see.)

**Comment by cdeil** [comment]
OK, thanks!

**Comment by johannct** [comment]
if we were to make a case that MINUIT should be more easily used in 
python ecosystems, we should strive to add it to scipy.optimize or as a 
scikit. This would entail having a separate build/release system for 
Minuit from ROOT. pyminuit and iminuit also have significantly different 
interfaces...

**Comment by cdeil** [comment]
@johannct – Adding `MINUIT` to `scipy.optimize` might be difficult. I don't know if they want the C++ code and there's the issue that MINUIT is LGPL licensed and as far as I know the `scipy` devs have made the choice not to include non-BSD code, even if LGPL and BSD are compatible at some level.

Probably the easiest way forward is to improve `iminuit` and add everything we want there (e.g. a `scipy.optimize.minimize` compatible interface).
